### ISSUE TITLE
Compatibility with Angular 10

### ISSUE THREAD

**Issue by jedmundo** [dirkluijk/ngx-typesafe-forms#8]
Hello, 

Good job with the library btw, we use it in our project but we wanted to upgrade to angular 10 but we get this error during **runtime**:

ERROR Error: Uncaught (in promise): TypeError: Class constructor FormControl cannot be invoked without 'new'
TypeError: Class constructor FormControl cannot be invoked without 'new'
    at new FormControl (ngx-typesafe-forms.js:583)
    at new LoginComponent (login.component.ts:13)

**Comment by dirkluijk** [comment]
Sorry, I didn't do a lot of frontend over the past months, so I kind of forgot to update the dependencies. I just released `1.1.0` which should be compatible with Angular 10. Can you verify?

**Comment by xuxicheta** [comment]
I have the same error on Angular 8 when I extend my own class from typesafe FormGroup.
And only in prod mode.

It is not appears if `"target": "es2015"`,

**Comment by FrancescoBorzi** [comment]
@dirkluijk thanks, it's working with Angular 10 now. This issue can be closed

**Comment by FrancescoBorzi** [comment]
has the project been abandoned?
